module.exports = function countries() {
  return [
    { name: 'Poland', yt: 'yfUJ2eDm6ng' },
    { name: 'Estonia', yt: '76KOUIfDry8' },
    { name: 'Finland', yt: 'y4xlvh6qW6M' },
    { name: 'Spain', yt: 'nO4mDiJRH6Q' },
    { name: 'Netherlands', yt: 'kLL9IlQ_7OA' },
    { name: 'Germany', yt: 'o_xTETHwIQg' },
    { name: 'Italy', yt: 'zguJGdoPPnw' },
    { name: 'France', yt: 'dHb-gWC-WTc' },
    { name: 'Ukraine', yt: 'E1yoAtjhkzQ' },
    { name: 'United Kingdom', yt: 'K--kIdOpbJM' },
    { name: 'Latvia', yt: 'uBlZsGxeXk4' },
    { name: 'Romania', yt: 'lZp6QwWDQ4c' },
    { name: 'Hungary', yt: '6unRU5ZHbqY' },
    { name: 'Moldova', yt: 'pKLKeVC-9Y4' },
    { name: 'Serbia', yt: 'WkOFnIjGrkw' },
    { name: 'Malta', yt: 'E_0ugf0eP1Q' },
    { name: 'Slovenia', yt: 'Y-Q4Fh54wUk' },
    { name: 'Switzerland', yt: 'YLWDqy1DnP0' },
    { name: 'Czech Republic', yt: '9zZPB3y70oU' },
    { name: 'Belarus', yt: 'YU2My4BPX34' },
    { name: 'Azebaijan', yt: 'kWomOdDGwMM' },
    { name: 'Greece', yt: 'z6hvV9-Gi_w' },
    { name: 'Denmark', yt: 'XeraDSzu0nw' },
    { name: 'San Marino', yt: 'ZNflc1Zcw2A' },
    { name: 'Iceland', yt: 'nloweviD_90' },
    { name: 'Montenegro', yt: 'qxJoxbo9lCQ' },
    { name: 'Albania', yt: 'E7t4mu0tmWc' },
    { name: 'Georgia', yt: 'TuCZMdfBqm4' },
    { name: 'Austria', yt: 'I8MyztgOTv8' },
    { name: 'Armenia', yt: 'olpi6UGmm_Y' },
    { name: 'Cyprus', yt: 'eDSgs6syrgg' },
    { name: 'Ireland', yt: 'XAEjQXzW4Uc' },
    { name: 'Bulgaria', yt: 'Uvy_R3fTHQ4' },
    { name: 'Sweden', yt: 'U2UmYBkszOA' },
    { name: 'Australia', yt: 'J4XZxbrvepw' },
    { name: 'Russia', yt: 'bgBwbr_fUxA' },
    { name: 'Belgium', yt: '6DGf9TMehi0' },
    { name: 'Israel', yt: 'CziHrYYSyPc' },
    { name: 'Croatia', yt: '19Yo86KCd0w' },
    { name: 'Norway', yt: 'Mvxni-WcD9A' },
    { name: 'Portugal', yt: 'kaVp4El9p3s' },
    { name: 'Lithuania', yt: 'CvG3sdGdGUA' },
    { name: 'F.Y.R. Macedonia', yt: 'hJ8vStigz7k' }
  ];
};
